"""Error catalog (spec §54) — generated by hand from the specification.

Each user-facing error MUST provide: summary, data impact, recommended action,
diagnostics affordance and a stable code. Stack traces belong in "Developer
details" only. Codes are stable: never renumber, only append.
"""

from __future__ import annotations

from dataclasses import dataclass

from acet.domain.enums import FailureFamily, OperationOutcome


@dataclass(frozen=True)
class ErrorSpec:
    code: str
    summary: str
    family: FailureFamily
    outcome: OperationOutcome
    impact: str
    action: str


def _e(
    code: str, summary: str, family: FailureFamily, outcome: OperationOutcome, impact: str, action: str
) -> ErrorSpec:
    return ErrorSpec(code, summary, family, outcome, impact, action)


F = FailureFamily
Out = OperationOutcome

CATALOG: dict[str, ErrorSpec] = {
    e.code: e
    for e in (
        _e(
            "ACET-IMP-001",
            "Source inaccessible",
            F.INPUT,
            Out.PERMANENT_FAILURE,
            "Nothing was imported; no partial build was committed.",
            "Check that the file or folder exists and is readable, then retry the import.",
        ),
        _e(
            "ACET-IMP-002",
            "Hash mismatch après copie",
            F.INTEGRITY,
            Out.INTEGRITY_FAILURE,
            "The copy was discarded; nothing was committed.",
            "The source changed during import or the disk is unreliable. Retry; run Doctor if it persists.",
        ),
        _e(
            "ACET-IMP-003",
            "Espace disque insuffisant",
            F.RESOURCE,
            Out.RESOURCE_EXHAUSTED,
            "Nothing was committed.",
            "Free disk space or move the workspace, then retry.",
        ),
        _e(
            "ACET-STO-001",
            "Artifact manquant",
            F.STORAGE,
            Out.INTEGRITY_FAILURE,
            "Analyses depending on this artifact are blocked.",
            "Re-import the original file or restore the workspace from backup; run Doctor reconcile.",
        ),
        _e(
            "ACET-STO-002",
            "Artifact corrompu",
            F.INTEGRITY,
            Out.INTEGRITY_FAILURE,
            "The artifact is marked CORRUPTED and analysis is blocked.",
            "Re-import the original file (identical bytes repair it) or restore from backup.",
        ),
        _e(
            "ACET-DB-001",
            "Integrity check failed",
            F.DATABASE,
            Out.INTEGRITY_FAILURE,
            "The workspace opens in RECOVERY_READ_ONLY mode.",
            "Run Doctor and restore the latest validated backup.",
        ),
        _e(
            "ACET-DB-002",
            "Migration failed",
            F.MIGRATION,
            Out.PERMANENT_FAILURE,
            "The migration was rolled back; the previous database state is preserved.",
            "Open the workspace with the previous ACET version and send a diagnostic package.",
        ),
        _e(
            "ACET-GHD-001",
            "Ghidra unavailable",
            F.ENGINE,
            Out.SKIPPED_UNSUPPORTED,
            "Profiles requiring disassembly are unavailable (DEGRADED).",
            "Install or repair the Engine Pack.",
        ),
        _e(
            "ACET-GHD-002",
            "Ghidra timeout",
            F.TIMEOUT,
            Out.PARTIAL,
            "Validated facts are kept; extraction is marked partial.",
            "Retry with a longer timeout profile.",
        ),
        _e(
            "ACET-GHD-003",
            "Ghidra worker crash",
            F.ENGINE,
            Out.RETRYABLE_FAILURE,
            "Validated facts are kept; the processor run failed.",
            "Retry; send diagnostics if it persists.",
        ),
        _e(
            "ACET-DIF-001",
            "Diff provider unavailable",
            F.ENGINE,
            Out.SKIPPED_UNSUPPORTED,
            "The run continues with reduced coverage (missing_evidence).",
            "Install the provider or accept partial results.",
        ),
        _e(
            "ACET-DIF-002",
            "Input incompatible",
            F.COMPATIBILITY,
            Out.SKIPPED_INCOMPATIBLE,
            "The provider was skipped for this input.",
            "No action required; see the run coverage.",
        ),
        _e(
            "ACET-JOB-001",
            "Worker heartbeat lost",
            F.TIMEOUT,
            Out.RETRYABLE_FAILURE,
            "The job was stopped; completed checkpoints are kept.",
            "Retry the job.",
        ),
        _e(
            "ACET-JOB-002",
            "Job interrupted",
            F.CANCELLATION,
            Out.INTERRUPTED,
            "Completed checkpoints are kept.",
            "Resume the job from the Jobs page or `acet jobs resume`.",
        ),
        _e(
            "ACET-PACK-001",
            "Pack checksum invalid",
            F.SECURITY,
            Out.SECURITY_REJECTION,
            "The pack was refused; nothing was imported.",
            "Obtain an intact copy of the pack.",
        ),
        _e(
            "ACET-UPD-001",
            "Engine pack incompatible",
            F.COMPATIBILITY,
            Out.SKIPPED_INCOMPATIBLE,
            "The Engine Pack was not activated.",
            "Install a compatible Engine Pack version.",
        ),
        _e(
            "ACET-PACK-002",
            "Pack schema newer than this ACET",
            F.COMPATIBILITY,
            Out.SKIPPED_INCOMPATIBLE,
            "The pack was refused; nothing was imported (ACET-FMT-002).",
            "Open it with a newer ACET version.",
        ),
        _e(
            "ACET-SEC-002",
            "Archive exceeds safety limits",
            F.SECURITY,
            Out.SECURITY_REJECTION,
            "Extraction was refused before writing anything.",
            "Do not trust this archive.",
        ),
        _e(
            "ACET-UPD-002",
            "Rollback unavailable",
            F.UPDATE,
            Out.PERMANENT_FAILURE,
            "Nothing was changed.",
            "No previous application version is recorded; reinstall the desired version.",
        ),
        _e(
            "ACET-SEC-001",
            "Unsafe archive path",
            F.SECURITY,
            Out.SECURITY_REJECTION,
            "Extraction was refused before writing anything.",
            "Do not trust this archive.",
        ),
        _e(
            "ACET-REP-001",
            "Report generation failed",
            F.EXPORT,
            Out.PERMANENT_FAILURE,
            "No partial report was written.",
            "Check destination permissions and space, then retry.",
        ),
        # Additions beyond §54 (allowed: append-only). Kept in the same families.
        _e(
            "ACET-IMP-004",
            "Build already exists",
            F.INPUT,
            Out.SKIPPED_POLICY,
            "Nothing was created.",
            "Choose: add an observation to the existing build, open it, or cancel (ACET-IMP-004).",
        ),
        _e(
            "ACET-IMP-005",
            "Unsupported or unsafe source path",
            F.INPUT,
            Out.SECURITY_REJECTION,
            "Nothing was imported.",
            "Point the import at regular files inside a readable folder.",
        ),
        _e(
            "ACET-WS-001",
            "Workspace not found or invalid",
            F.CONFIGURATION,
            Out.PERMANENT_FAILURE,
            "No data was modified.",
            "Create a workspace with `acet workspace create` or pass --workspace.",
        ),
        _e(
            "ACET-DB-003",
            "Database schema is newer than this ACET",
            F.COMPATIBILITY,
            Out.SKIPPED_INCOMPATIBLE,
            "The workspace was opened read-only or refused; nothing was written.",
            "Use the ACET version that created this workspace or a newer one.",
        ),
        _e(
            "ACET-DOM-001",
            "Illegal state transition",
            F.INTERNAL,
            Out.INTERNAL_INVARIANT_VIOLATION,
            "The transition was refused; nothing was persisted.",
            "Send a diagnostic package.",
        ),
        _e(
            "ACET-PROF-001",
            "Invalid product profile",
            F.CONFIGURATION,
            Out.PERMANENT_FAILURE,
            "The profile was refused.",
            "Fix the profile: only declarative keys of schema v2 are allowed.",
        ),
        _e(
            "ACET-NOTFOUND-001",
            "Object not found",
            F.INPUT,
            Out.PERMANENT_FAILURE,
            "No data was modified.",
            "Check the identifier.",
        ),
        _e(
            "ACET-INT-001",
            "Internal invariant violation",
            F.INTERNAL,
            Out.INTERNAL_INVARIANT_VIOLATION,
            "The operation was aborted.",
            "Send a diagnostic package.",
        ),
    )
}


class AcetError(Exception):
    """Error carrying a stable catalog code (ACET-CLOSE-002/003)."""

    def __init__(self, code: str, detail: str | None = None, *, data: dict[str, object] | None = None) -> None:
        spec = CATALOG.get(code)
        if spec is None:
            spec = CATALOG["ACET-INT-001"]
            detail = f"unknown error code {code!r}: {detail}"
        self.spec = spec
        self.code = spec.code
        self.detail = detail
        self.data = dict(data or {})
        super().__init__(f"{spec.code}: {spec.summary}" + (f" — {detail}" if detail else ""))

    @property
    def family(self) -> FailureFamily:
        return self.spec.family

    @property
    def outcome(self) -> OperationOutcome:
        return self.spec.outcome

    def to_dict(self) -> dict[str, object]:
        return {
            "code": self.code,
            "summary": self.spec.summary,
            "detail": self.detail,
            "family": self.family.value,
            "outcome": self.outcome.value,
            "impact": self.spec.impact,
            "action": self.spec.action,
            **({"data": self.data} if self.data else {}),
        }


def classify_exception(exc: BaseException) -> AcetError:
    """Map any exception onto the closed taxonomy (ACET-CLOSE-002, ACC-103)."""
    from acet.domain.state_machines import DomainTransitionError

    if isinstance(exc, AcetError):
        return exc
    if isinstance(exc, DomainTransitionError):
        return AcetError("ACET-DOM-001", str(exc))
    if isinstance(exc, FileNotFoundError | PermissionError | IsADirectoryError):
        return AcetError("ACET-IMP-001", type(exc).__name__)
    if isinstance(exc, OSError) and getattr(exc, "errno", None) == 28:  # ENOSPC
        return AcetError("ACET-IMP-003", "ENOSPC")
    return AcetError("ACET-INT-001", f"{type(exc).__name__}: {exc}")
