"""Identifiers (spec §7).

* Artifacts are identified by lowercase hex SHA-256.
* Every other entity uses UUIDv7 (RFC 9562). Per ACET-TIME-003 UUIDv7 ordering is
  ergonomic only and never the sole proof of causal order.
"""

from __future__ import annotations

import os
import re
import threading
import time
import uuid

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")

_lock = threading.Lock()
_last_ms = -1
_counter = 0


def uuid7() -> str:
    """Return a new UUIDv7 string.

    Uses a 12-bit monotonic counter in ``rand_a`` within the same millisecond so
    that IDs generated by this process are strictly increasing even if the wall
    clock stalls. If the clock goes backwards we keep the last timestamp
    (FI-008: clock anomaly must not break ordering of locally generated IDs).
    """
    global _last_ms, _counter
    with _lock:
        now_ms = time.time_ns() // 1_000_000
        if now_ms <= _last_ms:
            _counter += 1
            if _counter > 0xFFF:
                _last_ms += 1
                _counter = 0
            now_ms = _last_ms
        else:
            _last_ms = now_ms
            _counter = 0
        counter = _counter
    rand_b = int.from_bytes(os.urandom(8), "big") & ((1 << 62) - 1)
    value = (now_ms & ((1 << 48) - 1)) << 80
    value |= 0x7 << 76
    value |= counter << 64
    value |= 0b10 << 62
    value |= rand_b
    return str(uuid.UUID(int=value))


def is_uuid7(value: str) -> bool:
    try:
        parsed = uuid.UUID(value)
    except (ValueError, AttributeError, TypeError):
        return False
    return parsed.version == 7 and str(parsed) == value


def is_sha256(value: str) -> bool:
    """True if ``value`` is a canonical (lowercase hex) SHA-256 digest."""
    return isinstance(value, str) and bool(_SHA256_RE.match(value))


def require_sha256(value: str) -> str:
    if not is_sha256(value):
        raise ValueError(f"not a canonical lowercase SHA-256: {value!r}")
    return value
